name: Docker Image CI

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@ab83648e2e224cfeeab899e23b639660765c3a89
      uses: docker/build-push-action@v1.1.1
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: arekkas
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: "${{ secrets.DOCKER_SECRET_AREKKAS }}"
        # Docker repository to tag the image with
        repository: oryd/e2e-env
